apiVersion: apps/v1
kind: Deployment
metadata:
  name: nosql-app
  namespace: notice
  labels:
    app: nosql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nosql-app
      tier: backend
  template:
    metadata:
      name: nosql-app
      labels:
        app: nosql-app
        tier: backend
    spec:
      containers:
        - name: nosql-app
          image: docker.io/hyeopgeonlee/nosql-jdk17:0.0.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 11000
      restartPolicy: Always
